### ISSUE TITLE
Handle migration from scith/redirect_ynh

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/redirect_ynh#1]
The opi's redirect_ynh app has replaced the scith's one, but we need to handle update from one to another. The upgrade script should set a default value for `redirect_type` attribute, and `proxy` seems a good choice according to scith/redirect_ynh behavior. (sorry for this bad english, i'm exhausted)

**Comment by scith** [comment]
I can't test at the moment but what about changing https://github.com/YunoHost-Apps/redirect_ynh/blob/master/scripts/upgrade#L52-L53
to "else" (instead of "elif then")
It could do the trick

**Comment by opi** [comment]
I don't know how https://github.com/YunoHost-Apps/redirect_ynh/blob/master/scripts/upgrade#L26 behave if no setting is defined
