### ISSUE TITLE
blocked by IP

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/redirect_ynh#10]
Hello there, 

so i m using redirect with my yunohost to use an second serveur at home, and give https with let's encrypte to the second serveur at home it's a NAS.

the problem my nas can access it on internet.

i want bloc access to my redirect apps by ip, only my local network can accessit.

how add this filter acess please

**Comment by scith** [comment]
Hi
I don't think thats possible... YunoHost is meant to be available online.
You could cheat by using a fake domain (for instance google.com or nas.local) and then make your local DNS (router or hosts files) point this domain to your nas.
It would work very well. However, someone could do the same remotely (make google.com or nas.local point to your public IP) and that would make your nas again available online... But the attacker would need to know the local domain and the public IP though. In both cases, I would recommend to protect it under the SSO

**Comment by scith** [comment]
In any case, please allow me to close the issue as this isn't something we can do on the package itself. It is a specific scenario that may require specific adjustments to the conf fike
