### ISSUE TITLE
Can not redirect a second domain

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/redirect_ynh#12]
Bonjour

Je viens d’installer un serveur Proxmox 5.2 sous debian 9 avec plusieurs VMs. Dans une des VMs j’ai installer un YunoHost 2.7.12 (sous Debian 8) qui fonctionne bien.

Au moins dans 2 VMs, je vais installer un site sous Joomla. Comme j’ai qu’une seule adresse IP publique, j’ai choisi l’appli redirect_ynh pour rediriger mes différents sites vers mes IPs locales.

La première redirection vers mondomaine.tld a bien fonctionné mais quand je souhaite le faire avec mon second domaine www.mondomaine.tld ça ne fonctionne pas.

YunoHost me dit qu’il a rencontré une erreur interne :

**YunoHost a rencontré une erreur interne : **
Vraiment navré.
Vous devriez chercher de l’aide sur le forum ou le salon pour résoudre le problème, ou rapporter le bogue sur l’outil de suivi.
Les informations suivantes peuvent être utile à l’interlocuteur vous aidant :
Action

POST /apps
** {“locale”:“fr”,“app”:“redirect”,“args”:“domain=www.mondomaine.tld&path=%2F&redirect_path=http%3A%2F%2F192.168.0.50%3A8080&is_public=1&redirect_type=proxy”,“label”:“Redirect”}**

Trace

Traceback (most recent call last):
** File “/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py”, line 406, in process**
** ret = self.actionsmap.process(arguments, timeout=30, route=_route)**
** File “/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py”, line 498, in process**
** return func(arguments)
** File “/usr/lib/moulinette/yunohost/app.py”, line 690, in app_install**
** manifest, extracted_app_folder = _fetch_app_from_git(app)**
** File “/usr/lib/moulinette/yunohost/app.py”, line 1594, in _fetch_app_from_git**
** app_info[‘manifest’][‘lastUpdate’] = app_info[‘lastUpdate’]**
KeyError: 'lastUpdate’

Merci pour votre aide

Hello

I just installed a Proxmox 5.2 server under debian 9 with several VMs. In one of the VMs I install a YunoHost 2.7.12 (under Debian 8) that works well.

At least in 2 VMs, I will install a site under Joomla. As I have only one public IP address, I chose the redirect_ynh app to redirect my different sites to my local IPs.

The first redirection to mydomain.tld worked well but when I want to do it with my second domain www.mydomain.tld it does not work.

YunoHost tells me he has encountered an internal error:

** YunoHost has encountered an internal error: **
Really sorry.
You should look for help on the forum or the show to solve the problem, or report the bug on the tracking tool.
The following information may be useful to the person helping you:
Action
POST /apps
** {“locale”:“fr”,“app”:“redirect”,“args”:“domain=www.mondomaine.tld&path=%2F&redirect_path=http%3A%2F%2F192.168.0.50%3A8080&is_public=1&redirect_type=proxy”,“label”:“Redirect”}**

Trace

Traceback (most recent call last):
** File “/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py”, line 406, in process**
** ret = self.actionsmap.process(arguments, timeout=30, route=_route)**
** File “/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py”, line 498, in process**
** return func(arguments)
** File “/usr/lib/moulinette/yunohost/app.py”, line 690, in app_install**
** manifest, extracted_app_folder = _fetch_app_from_git(app)**
** File “/usr/lib/moulinette/yunohost/app.py”, line 1594, in _fetch_app_from_git**
** app_info[‘manifest’][‘lastUpdate’] = app_info[‘lastUpdate’]**
KeyError: 'lastUpdate’

Thanks for your help

**Comment by scith** [comment]
Bizarre, je n'ai pas ce problème. Tu installes depuis l'URL github? Tu as ajouté sinon le repo community?

**Comment by alexAubin** [comment]
Closing because that seems related to an issue inside YunoHost (`KeyError: 'lastUpdate’`, probably fixed since then) and not about this app in particular
