### ISSUE TITLE
All redirects are "private" after update

### ISSUE THREAD

**Issue by optikfluffel** [YunoHost-Apps/redirect_ynh#18]
I just ran `yunohost tools upgrade` and now all 3 of my redirects aren't public anymore, one has to be logged in to get to them. They worked fine up to that point.

I also got a warning (per redirect) while upgrading:

```
Warning: [WARN] Too many arguments ! "/" will be ignored.
```

Any idea what went wrong and how to fix this?

__// Edit:__
After completely removing and reinstalling them, they seem to work again. Still no idea what went wrong.

**Comment by alexAubin** [comment]
Hi,

can you elaborate on what type of redirection you're using ? (302, 301 or proxy)

**Comment by optikfluffel** [comment]
Proxy, to some service running at the same server.
