### ISSUE TITLE
Faire que la redirection conserve l'emplacement des sous-dossiers

### ISSUE THREAD

**Issue by LeoBoudet** [YunoHost-Apps/redirect_ynh#22]
exemple.com/contact -> www.exemple.com/contact
Si c'est possible ! Merci !

Léo

**Comment by inrepublica** [comment]
J'ai eu le même problème résolu dans ce post: https://forum.yunohost.org/t/resolu-redirection-du-www/10547

**Comment by zamentur** [comment]
Résolu
