### ISSUE TITLE
Reverse proxy to be completely transparent

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/redirect_ynh#23]
I use this app for reverse proxy from firstdomain to secondomain on another local server with yunohost.
I'm unable to connect to:
- seconddomain/yunohost/admin/
-> it shows the correct url but only accept firstdomain password (and contents is from firstdomain)
- seconddomain/app/admin
-> it shows seconddomain/app/ (even if url is still seconddomain/app/admin)
-> seconddomain/app/admin/pages is a 404

How to force it to send the complet request to the other server?

**Comment by arthurlutz** [comment]
Does the sencond server take into account some HTTP header to generate the correct URLs ?

**Comment by klorydryk** [comment]
I changed nothing on the nginx configuration of the second server. If I point the DMZ to this second server instead of the first one, everything works as expected.
Should I modified something on the second server config?

**Comment by arthurlutz** [comment]
Do I understand correctly you have two yunohost installs and want to chain them one behind the other ?

**Comment by klorydryk** [comment]
you're right.
