### ISSUE TITLE
Relative redirect

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/redirect_ynh#29]
I have domain.com and I want all requests to go to www.domain.com. So if user visits domain.com/path/whatever to redirect to www.domain.com/path/whatever.
Is this possible?

**Comment by NathanRHD** [comment]
(Not sure if possible, but I'm looking to do something similar!)

**Comment by tiotrom** [comment]
I did it manually by editing the etc/nginx/conf.d/website.d and adding this
```
location / {
    return 301 https://www.website.domain/$uri$is_args$args;

}
```

**Comment by h3ndrik** [comment]
i'd do `$request_uri` instead of `/$uri$is_args$args`

this should probably be fixed. i think most people wouldn't expect that a redirect throws away all path information.

Edit: there's already this pull request open: https://github.com/YunoHost-Apps/redirect_ynh/pull/27
