### ISSUE TITLE
Application quality level is low

### ISSUE THREAD

**Issue by niko2** [YunoHost-Apps/redirect_ynh#61]
App is working but has been flagged as low quality by yunohost, generating warnings and no upgrade possible.
I can help resolving this but I can't find how to check what is missing

**Comment by MadMan247** [comment]
Entirely speculative, but I'm guessing the testing suite changed something.

https://ci-apps.yunohost.org/ci/apps/redirect/

in particular, the last job was a failure https://ci-apps.yunohost.org/ci/job/30437

From a successful job:
![image](https://github.com/user-attachments/assets/c4de3a50-ab6b-4909-87d4-d0be84e5bd98)

From recent failure:
![image](https://github.com/user-attachments/assets/bed96646-a941-4122-92c6-76c6e02dc794)

In the failure, it looks like the testing script breaks. in a typical error, the syntax would more closely match the success, but would instead say "HTTP code: 502" or the like. (Maybe I'm wrong, idk.)

In this failure, we do get an error 302 (redirect/moved), which is the correct response provided from this app.

**Comment by niko2** [comment]
don't you think this is related to
`pycurl.error: (60, "SSL: certificate subject name (yunohost.org) does not match target host name '127.0.0.1'")`
and yunohost.org certificate has changed 2 days ago ?

maybe `redirect` test should use http, like `reverse proxy`

**Comment by sideeffectdk** [comment]
Just want to chime in that I'm getting the same notifications twice daily that this is flagged as broken.

**Comment by Salamandar** [comment]
Should be fixed in a few hours when the CI picks it up.
