### ISSUE TITLE
Blocking a Cross-Origin Request: The "Same Origin

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/redirect_ynh#9]
Hello there, 
i m using u apps to make a reverse proxy for a second serveur with apache without https.

on this serveur i have two apps : 

and when i try to using one and other i have this error : 

Blocking a Cross-Origin Request: The "Same Origin

do u know how pass this error code ?

i m using this program : 

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/44

thanks

**Comment by gamersalpha** [comment]
Hello there
he look like need this line in nginx : 


 Header set Access-Control-Allow-Origin: *



how do that please ?

**Comment by scith** [comment]
Hi
This could be added in the file /etc/nginx/conf.d/$domain.d/$app.conf
